require 'net/http'
require 'digest/sha1'
require 'thread'
require 'ipaddr'
require 'socket'
require 'timeout'
require_relative 'ruby-bencode/lib/bencode.rb'
require_relative 'client'
require_relative 'download_controller'
require_relative 'block_request_process'
require_relative 'incoming_request_process'
require_relative 'tracker'
require_relative 'peer'
require_relative 'bitfield'
require_relative 'message'
require_relative 'piece'
require_relative 'block'

Client.new(ARGV.first)